name: data_models
description: package to handle data models for the endeavor app
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <=3.10.4'

dependencies:
  cloud_firestore: ^4.7.0
  date_and_time_utilities:
    path: ../date_and_time_utilities
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_bloc: ^0.30.1
  formz: ^0.4.0
  server_data_models:
    path: ../server_data_models
