name: shim_data_service
description: temporary package to assist in switching over the data service
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <=3.10.4'

dependencies:
  authentication_repository:
    path: ../authentication_repository
  cached_query_flutter: ^2.1.1
  data_models:
    path: ../data_models
  grpc_data_service:
    path: ../grpc_data_service
  uuid: ^3.0.7
