name: grpc_data_service
description: Data service for the Endeavor package implemented in grpc
version: 1.0.0
publish_to: none

environment: 
  sdk: '>=3.0.0 <=3.10.4'

dependencies:
  authentication_repository:
    path: ../authentication_repository
  data_models:
    path: ../data_models
  grpc: ^3.2.4
  protobuf: ^3.1.0
