// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAc4DApbzvVY2sOt-pva4lDluHkbusaOw',
    appId: '1:219055418613:web:222b5a6c7d084f05b6a9bc',
    messagingSenderId: '219055418613',
    projectId: 'ecosystemauth',
    authDomain: 'ecosystemauth.firebaseapp.com',
    storageBucket: 'ecosystemauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnv3RyhZLBmPvlzBP_QsWsgJYkCX7xRT4',
    appId: '1:219055418613:android:17624a02076c7e40b6a9bc',
    messagingSenderId: '219055418613',
    projectId: 'ecosystemauth',
    storageBucket: 'ecosystemauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD16Wfgu99KtvS43ciHuTdwFeM47JjxcQ',
    appId: '1:219055418613:ios:28000fd086d2cc70b6a9bc',
    messagingSenderId: '219055418613',
    projectId: 'ecosystemauth',
    storageBucket: 'ecosystemauth.appspot.com',
    iosBundleId: 'com.example.endeavor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD16Wfgu99KtvS43ciHuTdwFeM47JjxcQ',
    appId: '1:219055418613:ios:28000fd086d2cc70b6a9bc',
    messagingSenderId: '219055418613',
    projectId: 'ecosystemauth',
    storageBucket: 'ecosystemauth.appspot.com',
    iosBundleId: 'com.example.endeavor',
  );
}
