// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3d6hgM8k8waUoMatHpaCe6O6mmZa7ACc',
    appId: '1:550787291975:web:13923c1b6dbe4c4fee8a62',
    messagingSenderId: '550787291975',
    projectId: 'endeavor-75fc7',
    authDomain: 'endeavor-75fc7.firebaseapp.com',
    storageBucket: 'endeavor-75fc7.appspot.com',
    measurementId: 'G-SSCBED9WQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6cvggjMzNtmvI3vgrq3MWeIduQdyVseM',
    appId: '1:550787291975:android:08a8b1c637ca3479ee8a62',
    messagingSenderId: '550787291975',
    projectId: 'endeavor-75fc7',
    storageBucket: 'endeavor-75fc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvm6ahH4RY3882FP9r03538_WB7rblQk',
    appId: '1:550787291975:ios:49194d425c747a3cee8a62',
    messagingSenderId: '550787291975',
    projectId: 'endeavor-75fc7',
    storageBucket: 'endeavor-75fc7.appspot.com',
    iosClientId: '550787291975-1ib9pelrjlmlri27gku1i8nhgqcpkvfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.endeavor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcvm6ahH4RY3882FP9r03538_WB7rblQk',
    appId: '1:550787291975:ios:49194d425c747a3cee8a62',
    messagingSenderId: '550787291975',
    projectId: 'endeavor-75fc7',
    storageBucket: 'endeavor-75fc7.appspot.com',
    iosClientId: '550787291975-1ib9pelrjlmlri27gku1i8nhgqcpkvfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.endeavor',
  );
}
