name: data_service
description: static firestore queries and server data type transformers
version: 1.0.0
publish_to: none


environment:
  sdk: '>=3.0.0 <=3.10.4'

dependencies:
  authentication_repository:
    path: ../authentication_repository
  cloud_functions: ^4.0.12
  collection: ^1.17.1
  data_models:
    path: ../data_models
  server_data_models:
    path: ../server_data_models
  cloud_firestore: ^4.7.0